name: CD - Deploy named instance
on:
  workflow_dispatch:
    inputs:
      instance:
        description: "Name of the instance of this service to provision"
        required: true
        type: string
defaults:
  run:
    shell: pwsh
env:
  ci_pipeline: true
  INSTANCE: ${{ github.event.inputs.instance }}
  GIT_ARM_CLIENT_ID: ${{ secrets.GIT_ARM_CLIENT_ID }}
  GIT_ARM_CLIENT_SECRET: ${{ secrets.GIT_ARM_CLIENT_SECRET }}
  GIT_ARM_TENANT_ID: ${{ secrets.GIT_ARM_TENANT_ID }}
  GIT_ARM_SUBSCRIPTION_ID: ${{ secrets.GIT_ARM_SUBSCRIPTION_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag_prefix: "" # Remove any prefix to ensure compatibility for all build types
          pre_release_branches: ^((?!main).)*$
      - name: Set calculated env vars
        run: |
          echo "RELEASE_VERSION=$(echo "${{ steps.tag_version.outputs.new_tag }}")" >> $GITHUB_ENV
        shell: bash
      - name: build.ps1 init
        run: ./build.ps1 init ${{ steps.tag_version.outputs.new_tag }} ci
      - name: build.ps1 compose
        run: ./build.ps1 compose ${{ steps.tag_version.outputs.new_tag }} ci
      - name: build.ps1 publish
        run: ./build.ps1 publish ${{ steps.tag_version.outputs.new_tag }} ci
      - name: build.ps1 deploy
        run: ./build.ps1 deploy ${{ steps.tag_version.outputs.new_tag }} ci
